# mcp_ai/mcp_streamlit/.streamlit/config.toml
[theme]
primaryColor="#1f6feb"
backgroundColor="#0b1220"
secondaryBackgroundColor="#0f172a"
textColor="#e2e8f0"
font="sans serif"

[browser]
gatherUsageStats=false